### ISSUE TITLE
Mod errors

### ISSUE THREAD

**Issue by RealBamboolord** [Dimensiondog/Agriculture-2-Abombs#2]
Scout obsoletes at tech Scientific Theory which does not exist!
Work Boats requires tech Sailing which does not exist!
Work Boats's unique "Cannot enter ocean tiles <before discovering [Astronomy]>" contains the conditional "before discovering [Astronomy]". This contains the parameter Astronomy which does not fit parameter type tech !
Trireme requires tech Sailing which does not exist!
Trireme obsoletes at tech Astronomy which does not exist!
Quinquereme requires tech Sailing which does not exist!
Quinquereme obsoletes at tech Astronomy which does not exist!
Dromon requires tech Sailing which does not exist!
Dromon obsoletes at tech Astronomy which does not exist!
Galley obsoletes at tech Astronomy which does not exist!
Chariot Archer obsoletes at tech Chivalry which does not exist!
War Chariot obsoletes at tech Chivalry which does not exist!
Horse Archer obsoletes at tech Chivalry which does not exist!
War Elephant obsoletes at tech Chivalry which does not exist!
Spearman obsoletes at tech Civil Service which does not exist!
Hoplite obsoletes at tech Civil Service which does not exist!
Persian Immortal obsoletes at tech Civil Service which does not exist!
Battering Ram obsoletes at tech Physics which does not exist!
Pictish Warrior obsoletes at tech Civil Service which does not exist!
Marauder obsoletes at tech Civil Service which does not exist!
Horseman requires tech Horseback Riding which does not exist!
Horseman obsoletes at tech Chivalry which does not exist!
Companion Cavalry requires tech Horseback Riding which does not exist!
Companion Cavalry obsoletes at tech Chivalry which does not exist!
African Forest Elephant requires tech Horseback Riding which does not exist!
African Forest Elephant obsoletes at tech Chivalry which does not exist!
Cataphract requires tech Horseback Riding which does not exist!
Cataphract obsoletes at tech Chivalry which does not exist!
Catapult obsoletes at tech Physics which does not exist!
Ballista obsoletes at tech Physics which does not exist!
Swordsman obsoletes at tech Steel which does not exist!
Legion obsoletes at tech Gunpowder which does not exist!
Mohawk Warrior obsoletes at tech Gunpowder which does not exist!
Pikeman requires tech Civil Service which does not exist!
Pikeman obsoletes at tech Gunpowder which does not exist!
Landsknecht requires tech Civil Service which does not exist!
Landsknecht obsoletes at tech Gunpowder which does not exist!
Galleass requires tech Compass which does not exist!
Galleass obsoletes at tech Navigation which does not exist!
Knight requires tech Chivalry which does not exist!
Knight obsoletes at tech Military Science which does not exist!
Camel Archer requires tech Chivalry which does not exist!
Camel Archer obsoletes at tech Military Science which does not exist!
Conquistador requires tech Chivalry which does not exist!
Conquistador obsoletes at tech Military Science which does not exist!
Naresuan's Elephant requires tech Chivalry which does not exist!
Naresuan's Elephant obsoletes at tech Military Science which does not exist!
Mandekalu Cavalry requires tech Chivalry which does not exist!
Mandekalu Cavalry obsoletes at tech Military Science which does not exist!
Keshik requires tech Chivalry which does not exist!
Keshik obsoletes at tech Military Science which does not exist!
Crossbowman obsoletes at tech Industrialization which does not exist!
Chu-Ko-Nu obsoletes at tech Industrialization which does not exist!
Longbowman obsoletes at tech Industrialization which does not exist!
Trebuchet requires tech Physics which does not exist!
Trebuchet obsoletes at tech Chemistry which does not exist!
Hwach'a requires tech Physics which does not exist!
Hwach'a obsoletes at tech Chemistry which does not exist!
Longswordsman requires tech Steel which does not exist!
Longswordsman obsoletes at tech Gunpowder which does not exist!
Samurai requires tech Steel which does not exist!
Samurai obsoletes at tech Gunpowder which does not exist!
Berserker obsoletes at tech Metallurgy which does not exist!
Caravel requires tech Astronomy which does not exist!
Caravel obsoletes at tech Combustion which does not exist!
Turtle Ship requires tech Astronomy which does not exist!
Turtle Ship obsoletes at tech Combustion which does not exist!
Musketman requires tech Gunpowder which does not exist!
Musketman obsoletes at tech Rifling which does not exist!
Musketeer requires tech Gunpowder which does not exist!
Musketeer obsoletes at tech Rifling which does not exist!
Janissary requires tech Gunpowder which does not exist!
Janissary obsoletes at tech Rifling which does not exist!
Minuteman requires tech Gunpowder which does not exist!
Minuteman obsoletes at tech Rifling which does not exist!
Tercio requires tech Gunpowder which does not exist!
Tercio obsoletes at tech Rifling which does not exist!
Privateer requires tech Navigation which does not exist!
Sea Beggar requires tech Navigation which does not exist!
Frigate requires tech Navigation which does not exist!
Frigate obsoletes at tech Electronics which does not exist!
Ship of the Line requires tech Navigation which does not exist!
Ship of the Line obsoletes at tech Electronics which does not exist!
Lancer requires tech Metallurgy which does not exist!
Lancer obsoletes at tech Combined Arms which does not exist!
Sipahi requires tech Metallurgy which does not exist!
Sipahi obsoletes at tech Combined Arms which does not exist!
Hakkapeliitta requires tech Metallurgy which does not exist!
Hakkapeliitta obsoletes at tech Combined Arms which does not exist!
Cannon requires tech Chemistry which does not exist!
Cannon obsoletes at tech Dynamite which does not exist!
Gatling Gun requires tech Industrialization which does not exist!
Gatling Gun obsoletes at tech Ballistics which does not exist!
Rifleman requires tech Rifling which does not exist!
Rifleman obsoletes at tech Replaceable Parts which does not exist!
Norwegian Ski Infantry requires tech Rifling which does not exist!
Norwegian Ski Infantry obsoletes at tech Replaceable Parts which does not exist!
Carolean requires tech Rifling which does not exist!
Carolean obsoletes at tech Replaceable Parts which does not exist!
Mehal Sefari requires tech Rifling which does not exist!
Mehal Sefari obsoletes at tech Replaceable Parts which does not exist!
Cavalry requires tech Military Science which does not exist!
Cavalry obsoletes at tech Combustion which does not exist!
Cossack requires tech Military Science which does not exist!
Cossack obsoletes at tech Combustion which does not exist!
Hussar requires tech Military Science which does not exist!
Hussar obsoletes at tech Combustion which does not exist!
Ironclad requires tech Steam Power which does not exist!
Ironclad obsoletes at tech Combustion which does not exist!
Artillery requires tech Dynamite which does not exist!
Submarine requires tech Refrigeration which does not exist!
Great War Infantry requires tech Replaceable Parts which does not exist!
Great War Infantry obsoletes at tech Plastics which does not exist!
Foreign Legion requires tech Replaceable Parts which does not exist!
Foreign Legion obsoletes at tech Plastics which does not exist!
Triplane requires tech Flight which does not exist!
Triplane obsoletes at tech Radar which does not exist!
Great War Bomber requires tech Flight which does not exist!
Great War Bomber obsoletes at tech Radar which does not exist!
Infantry requires tech Plastics which does not exist!
Infantry obsoletes at tech Mobile Tactics which does not exist!
Carrier requires tech Electronics which does not exist!
Battleship requires tech Electronics which does not exist!
Machine Gun requires tech Ballistics which does not exist!
Anti-Aircraft Gun requires tech Ballistics which does not exist!
Anti-Aircraft Gun obsoletes at tech Rocketry which does not exist!
Landship requires tech Combustion which does not exist!
Landship obsoletes at tech Combined Arms which does not exist!
Destroyer requires tech Combustion which does not exist!
Marine requires tech Pharmaceuticals which does not exist!
Fighter requires tech Radar which does not exist!
Zero requires tech Radar which does not exist!
Bomber requires tech Radar which does not exist!
B17 requires tech Radar which does not exist!
Paratrooper requires tech Radar which does not exist!
Tank requires tech Combined Arms which does not exist!
Panzer requires tech Combined Arms which does not exist!
Anti-Tank Gun requires tech Combined Arms which does not exist!
Atomic Bomb requires tech Nuclear Fission which does not exist!
Rocket Artillery requires tech Rocketry which does not exist!
Mobile SAM requires tech Rocketry which does not exist!
Guided Missile requires tech Advanced Ballistics which does not exist!
Nuclear Missile requires tech Advanced Ballistics which does not exist!
Helicopter Gunship requires tech Computers which does not exist!
Nuclear Submarine requires tech Telecommunications which does not exist!
Mechanized Infantry requires tech Mobile Tactics which does not exist!
Missile Cruiser requires tech Robotics which does not exist!
Modern Armor requires tech Lasers which does not exist!
Jet Fighter requires tech Lasers which does not exist!
Giant Death Robot requires tech Nuclear Fusion which does not exist!
Stealth Bomber requires tech Stealth which does not exist!
SS Booster requires tech Advanced Ballistics which does not exist!
SS Cockpit requires tech Satellites which does not exist!
SS Engine requires tech Particle Physics which does not exist!
SS Stasis Chamber requires tech Nanotechnology which does not exist!
Circus requires tech Trapping which does not exist!
Lighthouse requires tech Optics which does not exist!
The Great Lighthouse requires tech Optics which does not exist!
Stable requires tech Horseback Riding which does not exist!
Circus Maximus requires tech Horseback Riding which does not exist!
Amphitheater requires tech Drama and Poetry which does not exist!
National Epic requires tech Drama and Poetry which does not exist!
Petra's unique "[+6 Culture] [in this city] <after discovering [Archaeology]>" contains the conditional "after discovering [Archaeology]". This contains the parameter Archaeology which does not fit parameter type tech !
Aqueduct requires tech Engineering which does not exist!
Great Wall requires tech Engineering which does not exist!
Great Wall's unique "Enemy [Land] units must spend [1] extra movement points when inside your territory <before discovering [Dynamite]>" contains the conditional "before discovering [Dynamite]". This contains the parameter Dynamite which does not fit parameter type tech !
Garden requires tech Theology which does not exist!
Hagia Sophia requires tech Theology which does not exist!
Great Mosque of Djenne requires tech Theology which does not exist!
Grand Temple requires tech Theology which does not exist!
Chichen Itza requires tech Civil Service which does not exist!
National Treasury requires tech Guilds which does not exist!
Machu Picchu requires tech Guilds which does not exist!
Harbor requires tech Compass which does not exist!
University requires tech Education which does not exist!
Wat requires tech Education which does not exist!
Oxford University requires tech Education which does not exist!
Angkor Wat requires tech Education which does not exist!
Castle requires tech Chivalry which does not exist!
Mughal Fort requires tech Chivalry which does not exist!
Mughal Fort's unique "[+1 Gold] [in this city] <after discovering [Flight]>" contains the conditional "after discovering [Flight]". This contains the parameter Flight which does not fit parameter type tech !
Alhambra requires tech Chivalry which does not exist!
Notre Dame requires tech Physics which does not exist!
Armory requires tech Steel which does not exist!
Observatory requires tech Astronomy which does not exist!
Opera House requires tech Acoustics which does not exist!
Ceilidh Hall requires tech Acoustics which does not exist!
Sistine Chapel requires tech Acoustics which does not exist!
Bank requires tech Banking which does not exist!
Satrap's Court requires tech Banking which does not exist!
Forbidden Palace requires tech Banking which does not exist!
Theatre requires tech Printing Press which does not exist!
Leaning Tower of Pisa requires tech Printing Press which does not exist!
Himeji Castle requires tech Gunpowder which does not exist!
Seaport requires tech Navigation which does not exist!
Hermitage requires tech Architecture which does not exist!
Taj Mahal requires tech Architecture which does not exist!
Porcelain Tower requires tech Architecture which does not exist!
Windmill requires tech Economics which does not exist!
Coffee House requires tech Economics which does not exist!
Arsenal requires tech Metallurgy which does not exist!
Kremlin requires tech Metallurgy which does not exist!
Museum requires tech Archaeology which does not exist!
The Louvre requires tech Archaeology which does not exist!
Public School requires tech Scientific Theory which does not exist!
Factory requires tech Industrialization which does not exist!
Big Ben requires tech Industrialization which does not exist!
Military Academy requires tech Military Science which does not exist!
Brandenburg Gate requires tech Military Science which does not exist!
Hospital requires tech Biology which does not exist!
Stock Exchange requires tech Electricity which does not exist!
Hydro Plant requires tech Electricity which does not exist!
Stadium requires tech Refrigeration which does not exist!
Broadcast Tower requires tech Radio which does not exist!
Eiffel Tower requires tech Radio which does not exist!
Military Base requires tech Replaceable Parts which does not exist!
Statue of Liberty requires tech Replaceable Parts which does not exist!
Neuschwanstein requires tech Railroads which does not exist!
Research Lab requires tech Plastics which does not exist!
Cristo Redentor requires tech Plastics which does not exist!
Medical Lab requires tech Pharmaceuticals which does not exist!
Manhattan Project requires tech Atomic Theory which does not exist!
Pentagon requires tech Combined Arms which does not exist!
Solar Plant requires tech Ecology which does not exist!
Recycling Center requires tech Ecology which does not exist!
Sydney Opera House requires tech Ecology which does not exist!
Nuclear Plant requires tech Nuclear Fission which does not exist!
Apollo Program requires tech Rocketry which does not exist!
CN Tower requires tech Telecommunications which does not exist!
Bomb Shelter requires tech Telecommunications which does not exist!
Hubble Space Telescope requires tech Satellites which does not exist!
Spaceship Factory requires tech Robotics which does not exist!
United Nations requires tech Globalization which does not exist!
Horses revealed by tech Animal Husbandry which does not exist!
Coal revealed by tech Industrialization which does not exist!
Oil revealed by tech Biology which does not exist!
Aluminum revealed by tech Electricity which does not exist!
Uranium revealed by tech Atomic Theory which does not exist!
Farm's unique "[+1 Food] from [Fresh water] tiles <after discovering [Civil Service]>" contains the conditional "after discovering [Civil Service]". This contains the parameter Civil Service which does not fit parameter type tech !
Farm's unique "[+1 Food] from [non-fresh water] tiles <after discovering [Fertilizer]>" contains the conditional "after discovering [Fertilizer]". This contains the parameter Fertilizer which does not fit parameter type tech !
Lumber mill's unique "[+1 Production] <after discovering [Scientific Theory]>" contains the conditional "after discovering [Scientific Theory]". This contains the parameter Scientific Theory which does not fit parameter type tech !
Mine's unique "[+1 Production] <after discovering [Chemistry]>" contains the conditional "after discovering [Chemistry]". This contains the parameter Chemistry which does not fit parameter type tech !
Trading post requires tech Guilds which does not exist!
Trading post's unique "[+1 Gold] <after discovering [Economics]>" contains the conditional "after discovering [Economics]". This contains the parameter Economics which does not fit parameter type tech !
Camp requires tech Trapping which does not exist!
Camp's unique "[+1 Gold] <after discovering [Economics]>" contains the conditional "after discovering [Economics]". This contains the parameter Economics which does not fit parameter type tech !
Oil well requires tech Biology which does not exist!
Oil well's unique "Cannot be built on [Coast] tiles <before discovering [Refrigeration]>" contains the conditional "before discovering [Refrigeration]". This contains the parameter Refrigeration which does not fit parameter type tech !
Pasture requires tech Animal Husbandry which does not exist!
Pasture's unique "[+1 Food] <after discovering [Fertilizer]>" contains the conditional "after discovering [Fertilizer]". This contains the parameter Fertilizer which does not fit parameter type tech !
Plantation's unique "[+1 Food] <after discovering [Fertilizer]>" contains the conditional "after discovering [Fertilizer]". This contains the parameter Fertilizer which does not fit parameter type tech !
Quarry's unique "[+1 Production] <after discovering [Chemistry]>" contains the conditional "after discovering [Chemistry]". This contains the parameter Chemistry which does not fit parameter type tech !
Fishing Boats requires tech Sailing which does not exist!
Fishing Boats's unique "[+1 Gold] <after discovering [Compass]>" contains the conditional "after discovering [Compass]". This contains the parameter Compass which does not fit parameter type tech !
Fort requires tech Engineering which does not exist!
Railroad requires tech Railroads which does not exist!
Academy's unique "[+2 Science] <after discovering [Scientific Theory]>" contains the conditional "after discovering [Scientific Theory]". This contains the parameter Scientific Theory which does not fit parameter type tech !
Academy's unique "[+2 Science] <after discovering [Atomic Theory]>" contains the conditional "after discovering [Atomic Theory]". This contains the parameter Atomic Theory which does not fit parameter type tech !
Manufactory's unique "[+1 Production] <after discovering [Chemistry]>" contains the conditional "after discovering [Chemistry]". This contains the parameter Chemistry which does not fit parameter type tech !
Customs house's unique "[+1 Gold] <after discovering [Economics]>" contains the conditional "after discovering [Economics]". This contains the parameter Economics which does not fit parameter type tech !
Moai's unique "[+1 Gold] <after discovering [Flight]>" contains the conditional "after discovering [Flight]". This contains the parameter Flight which does not fit parameter type tech !
Terrace farm's unique "[+1 Food] from [Fresh water] tiles <after discovering [Civil Service]>" contains the conditional "after discovering [Civil Service]". This contains the parameter Civil Service which does not fit parameter type tech !
Terrace farm's unique "[+1 Food] from [non-fresh water] tiles <after discovering [Fertilizer]>" contains the conditional "after discovering [Fertilizer]". This contains the parameter Fertilizer which does not fit parameter type tech !
Polder requires tech Guilds which does not exist!
Polder's unique "[+1 Production, +2 Gold] <after discovering [Economics]>" contains the conditional "after discovering [Economics]". This contains the parameter Economics which does not fit parameter type tech !
Unknown era Ancient era referenced in column of tech Sedentry Lifestyle
Unknown era Ancient era referenced in column of tech Archery
Unknown era Ancient era referenced in column of tech Negotiation
Unknown era Ancient era referenced in column of tech Ideograms
Unknown era Ancient era referenced in column of tech Agriculture
Unknown era Ancient era referenced in column of tech Community
Unknown era Ancient era referenced in column of tech Naval Warfare
Unknown era Ancient era referenced in column of tech Taxonomy
Unknown era Ancient era referenced in column of tech Pottery
Unknown era Ancient era referenced in column of tech Bread Making
Unknown era Ancient era referenced in column of tech Consciousness
Unknown era Ancient era referenced in column of tech Folk Music
Unknown era Ancient era referenced in column of tech Folk Dance
Unknown era Ancient era referenced in column of tech Caste System
Unknown era Ancient era referenced in column of tech Fungiculture
Unknown era Ancient era referenced in column of tech Apiculture
Unknown era Ancient era referenced in column of tech Mining
Unknown era Ancient era referenced in column of tech The Wheel
Unknown era Ancient era referenced in column of tech Ancestor Worship
Unknown era Ancient era referenced in column of tech Exploration
Unknown era Ancient era referenced in column of tech Orchards
Unknown era Ancient era referenced in column of tech Chariotry
Unknown era Ancient era referenced in column of tech Standardisation
Unknown era Ancient era referenced in column of tech Heritage
Unknown era Ancient era referenced in column of tech Sacrifice Cult
Unknown era Ancient era referenced in column of tech Mummification
Unknown era Ancient era referenced in column of tech Stargazing
Unknown era Ancient era referenced in column of tech Trade
Unknown era Ancient era referenced in column of tech Fermentation
Unknown era Ancient era referenced in column of tech Copper Working
Unknown era Ancient era referenced in column of tech Pulley
Unknown era Ancient era referenced in column of tech Masonry
Unknown era Ancient era referenced in column of tech Lead Working
Unknown era Ancient era referenced in column of tech Board Games
Unknown era Ancient era referenced in column of tech Folk Medicine
Unknown era Ancient era referenced in column of tech Oil Lamps
Unknown era Ancient era referenced in column of tech Plough
Unknown era Ancient era referenced in column of tech Metal Casting
Unknown era Ancient era referenced in column of tech Textile Loom
Unknown era Ancient era referenced in column of tech Salt Processing
Unknown era Ancient era referenced in column of tech Ceremony
Unknown era Ancient era referenced in column of tech Soap Making
Unknown era Ancient era referenced in column of tech Piracy
Unknown era Ancient era referenced in column of tech Irrigation
Sculpture requires tech Textile Looms which does not exist!
Unknown era Ancient era referenced in column of tech Sculpture
Sericulture requires tech Textile Looms which does not exist!
Unknown era Ancient era referenced in column of tech Sericulture
Unknown era Ancient era referenced in column of tech Priesthood
Unknown era Ancient era referenced in column of tech Gardening
Unknown era Ancient era referenced in column of tech Leisure
Unknown era Ancient era referenced in column of tech Ornamentation
Unknown era Ancient era referenced in column of tech Duelism
Unknown era Ancient era referenced in column of tech Oratory
Unknown era Ancient era referenced in column of tech Divination
Unknown era Ancient era referenced in column of tech Candle Making
Unknown era Ancient era referenced in column of tech Specialisation
Unknown era Ancient era referenced in column of tech Sundial
Unknown era Ancient era referenced in column of tech Furniture Making
Unknown era Ancient era referenced in column of tech Writing
Unknown era Ancient era referenced in column of tech Matriarchy
Unknown era Ancient era referenced in column of tech Ressurection
Unknown era Ancient era referenced in column of tech Locks
Unknown era Ancient era referenced in column of tech Bronze Working
Unknown era Ancient era referenced in column of tech Plumbing
Unknown era Ancient era referenced in column of tech Gear
Unknown era Ancient era referenced in column of tech Cuisine
Unknown era Ancient era referenced in column of tech Monotheism
Unknown era Ancient era referenced in column of tech Patriarchy
Unknown era Ancient era referenced in column of tech Magic
Unknown era Ancient era referenced in column of tech Seafaring
Unknown era Ancient era referenced in column of tech Brass Working
Unknown era Ancient era referenced in column of tech Central Heating
Unknown era Ancient era referenced in column of tech Hydraulic Mining
Unknown era Ancient era referenced in column of tech Scriptures
Unknown era Ancient era referenced in column of tech Karma
Unknown era Ancient era referenced in column of tech Ventinary Medicine
Unknown era Ancient era referenced in column of tech Polytheism
Unknown era Ancient era referenced in column of tech Cloud Patterns
Unknown era Ancient era referenced in column of tech Linguistics
Unknown era Ancient era referenced in column of tech Glassblowing
Unknown era Ancient era referenced in column of tech Monarchy
Unknown era Ancient era referenced in column of tech Reincarnation
Classical Lifestyle requires tech Glass Blowing which does not exist!
Unknown era Classical era referenced in column of tech Classical Lifestyle
Unknown era Classical era referenced in column of tech Ship Building
Unknown era Classical era referenced in column of tech Aristocracy
Unknown era Classical era referenced in column of tech Military Training
Unknown era Classical era referenced in column of tech Iron Working
Unknown era Classical era referenced in column of tech Mathematics
Unknown era Classical era referenced in column of tech Currency
Unknown era Classical era referenced in column of tech Mail
Unknown era Classical era referenced in column of tech Alphabet
Unknown era Classical era referenced in column of tech Meditation
Unknown era Classical era referenced in column of tech Horse Breeding
Unknown era Classical era referenced in column of tech Ancient Machinery
Unknown era Classical era referenced in column of tech Athletics
Unknown era Classical era referenced in column of tech Geometry
Unknown era Classical era referenced in column of tech Road Building
Unknown era Classical era referenced in column of tech Cyrptography
Unknown era Classical era referenced in column of tech Literature
Unknown era Classical era referenced in column of tech Code of Laws
Unknown era Clasical era referenced in column of tech Mounted Archery
Unknown era Clasical era referenced in column of tech Stirrups
Unknown era Clasical era referenced in column of tech Combat Sports
Unknown era Clasical era referenced in column of tech Calendar
Unknown era Clasical era referenced in column of tech City Planning
Unknown era Clasical era referenced in column of tech Construction
Law Enforcement requires tech Cryptography which does not exist!
Unknown era Clasical era referenced in column of tech Law Enforcement
Unknown era Clasical era referenced in column of tech Diplomacy
Unknown era Clasical era referenced in column of tech Democracy
Unknown era Clasical era referenced in column of tech Spice Trade
Unknown era Clasical era referenced in column of tech Astrology
Unknown era Clasical era referenced in column of tech Calligraphy
Unknown era Clasical era referenced in column of tech Ancient Ballistics
Unknown era Clasical era referenced in column of tech Concrete
Unknown era Clasical era referenced in column of tech Ancient Medicine
Unknown era Clasical era referenced in column of tech Meritocracy
Unknown era Classical era referenced in column of tech Drug Trade
Unknown era Classical era referenced in column of tech Canal System
Unknown era Classical era referenced in column of tech Siege Warfare
Unknown era Classical era referenced in column of tech Philosophy
Unknown era Classical era referenced in column of tech Aesthetics
Unknown era Classical era referenced in column of tech Insurance
Unknown era Classical era referenced in column of tech Drama
Unknown era Classical era referenced in column of tech Floristry
Unknown era Classical era referenced in column of tech Mosaic Working
Sanitation requires tech Canal Systems which does not exist!
Unknown era Classical era referenced in column of tech Sanitation
Unknown era Classical era referenced in column of tech Machinery
Unknown era Classical era referenced in column of tech Weather Lore
Unknown era Classical era referenced in column of tech Musical Notation
Unknown era Classical era referenced in column of tech Poetry
Unknown era Classical era referenced in column of tech Paved Roads
Unknown era Classical era referenced in column of tech Waterwheels
Unknown era Classical era referenced in column of tech Geocentrism
Future Tech requires tech Globalization which does not exist!
Future Tech requires tech Stealth which does not exist!
Future Tech requires tech Nuclear Fusion which does not exist!
Future Tech requires tech Particle Physics which does not exist!
Future Tech requires tech Nanotechnology which does not exist!
Religious Texts's unique "[+34]% Natural religion spread [in all cities] <after discovering [Printing Press]>" contains the conditional "after discovering [Printing Press]". This contains the parameter Printing Press which does not fit parameter type tech !
French Republic's unique "[+2 Culture] [in all cities] <before discovering [Steam Power]>" contains the conditional "before discovering [Steam Power]". This contains the parameter Steam Power which does not fit parameter type tech !
Kingdom of Hawaii's unique "Enables embarkation for land units <starting from the [Ancient era]>" contains the conditional "starting from the [Ancient era]". This contains the parameter Ancient era which does not fit parameter type era !
Kingdom of Hawaii's unique "Enables [All] units to enter ocean tiles <starting from the [Ancient era]>" contains the conditional "starting from the [Ancient era]". This contains the parameter Ancient era which does not fit parameter type era !
Gran Colombia's unique "Receive a free Great Person at the end of every [Maya Long Count calendar cycle] (every 394 years), after researching [Theology]. Each bonus person can only be chosen once." contains parameter Theology, which does not fit parameter type tech !
Tradition requires era Ancient era which does not exist!
Liberty requires era Ancient era which does not exist!
Honor requires era Ancient era which does not exist!
Piety requires era Classical era which does not exist!
discover a lost technology's unique "[1] free random researchable Tech(s) from the [Ancient era]" contains parameter Ancient era, which does not fit parameter type era !
Camp has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Pasture has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Plantation has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Quarry has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Road has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Railroad has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Academy has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Landmark has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Manufactory has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Customs house has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Holy site has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Citadel has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Moai has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Ancient ruins has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
City ruins has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
City center has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Barbarian encampment has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Kingdom of Italy's unique "[+12] [Production] [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% [stat] [cityFilter]"
Peace Loving's unique "[+1 Happiness] for every [5] global followers [in non-enemy foreign cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
Tithe's unique "[+1 Gold] for every [4] global followers [in all cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
World Church's unique "[+1 Culture] for every [5] global followers [in foreign cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
Kingdom of Italy's unique "[+12] [Production] [in all cities]" looks like it may be a misspelling of:
	"[relativeAmount]% [stat] [cityFilter]"
Piety Complete's unique "[Faith] cost of purchasing items in cities [-20]% " looks like it may be a misspelling of:
	"[stat] cost of purchasing items in cities [relativeAmount]%"

**Comment by Dimensiondog** [comment]
100% expected
I'm still working on the tech tree so everything dependent on techs won't work yet. A working version of the mod will take a month maybe a month and a half, let me know on the discord if you'd like to help since that would speed up the process.
